abcschool/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("core.urls", namespace="core")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("employees/", include("employees.urls", namespace="employees")),
        path("students/", include("students.urls", namespace="students")),
        path("accounting/", include("accounting.urls", namespace="accounting")),
        path("reports/", include("reports.urls", namespace="reports")),
        path("fees/", include("fees.urls", namespace="fees")),
        path("exams/", include("exams.urls", namespace="exams")),
        path("tasks/", include("tasks.urls", namespace="tasks")),
        path("courses/", include("courses.urls", namespace="courses")),
        path("hrms/", include("hrms.urls", namespace="hrms")),
        path("accounts/", include("registration.backends.default.urls")),
        path("tinymce/", include("tinymce.urls")),
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "ABC School Administration"
admin.site.site_title = "ABC School Admin Portal"
admin.site.index_title = "Welcome to ABC School Admin Portal"

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("suggestions/", views.SuggestionListView.as_view(), name="suggestion_list"),
    path(
        "suggestion/<str:pk>/",
        views.SuggestionDetailView.as_view(),
        name="suggestion_detail",
    ),
    path(
        "new/suggestion/",
        views.SuggestionCreateView.as_view(),
        name="suggestion_create",
    ),
    path(
        "suggestion/<str:pk>/update/",
        views.SuggestionUpdateView.as_view(),
        name="suggestion_update",
    ),
    path(
        "suggestion/<str:pk>/delete/",
        views.SuggestionDeleteView.as_view(),
        name="suggestion_delete",
    ),
]

students/urls.py
from django.urls import path

from . import views

app_name = "students"

urlpatterns = [
    #ajax 
    path("get-divisions/", views.get_divisions, name="get_divisions"),
    path("", views.StudentListView.as_view(), name="student_list"),
    path("student/<str:pk>/", views.StudentDetailView.as_view(), name="student_detail"),
    path("new/student/", views.StudentCreateView.as_view(), name="student_create"),
    path(
        "new/student/<str:pk>/",
        views.StudentCreateView.as_view(),
        name="student_create",
    ),
    path(
        "student/<str:pk>/update/",
        views.StudentUpdateView.as_view(),
        name="student_update",
    ),
    path(
        "student/<str:pk>/delete/",
        views.StudentDeleteView.as_view(),
        name="student_delete",
    ),
    path(
        "studentfeestatements/",
        views.StudentFeeStatementListView.as_view(),
        name="studentfeestatement_list",
    ),
    path(
        "studentfeestatement/<str:pk>/",
        views.StudentFeeStatementDetailView.as_view(),
        name="studentfeestatement_detail",
    ),
    path(
        "new/studentfeestatement/",
        views.StudentFeeStatementCreateView.as_view(),
        name="studentfeestatement_create",
    ),
    path(
        "studentfeestatement/<str:pk>/update/",
        views.StudentFeeStatementUpdateView.as_view(),
        name="studentfeestatement_update",
    ),
    path(
        "studentfeestatement/<str:pk>/delete/",
        views.StudentFeeStatementDeleteView.as_view(),
        name="studentfeestatement_delete",
    ),
    path(
        "academic_year_student_fees/",
        views.AcademicYearStudentFeeListView.as_view(),
        name="academic_year_student_fee_list",
    ),
    path(
        "academic_year_student_fee/<str:pk>/",
        views.AcademicYearStudentFeeDetailView.as_view(),
        name="academic_year_student_fee_detail",
    ),
    path(
        "new/academic_year_student_fee/",
        views.AcademicYearStudentFeeCreateView.as_view(),
        name="academic_year_student_fee_create",
    ),
    path(
        "academic_year_student_fee/<str:pk>/update/",
        views.AcademicYearStudentFeeUpdateView.as_view(),
        name="academic_year_student_fee_update",
    ),
    path(
        "academic_year_student_fee/<str:pk>/delete/",
        views.AcademicYearStudentFeeDeleteView.as_view(),
        name="academic_year_student_fee_delete",
    ),
    path("standards/", views.StandardListView.as_view(), name="standard_list"),
    path("standard/<str:pk>/", views.StandardDetailView.as_view(), name="standard_detail"),
    path("new/standard/", views.StandardCreateView.as_view(), name="standard_create"),
    path(
        "standard/<str:pk>/update/",
        views.StandardUpdateView.as_view(),
        name="standard_update",
    ),
    path(
        "standard/<str:pk>/delete/",
        views.StandardDeleteView.as_view(),
        name="standard_delete",
    ),
    path("divisions/", views.DivisionListView.as_view(), name="division_list"),
    path("division/<str:pk>/", views.DivisionDetailView.as_view(), name="division_detail"),
    path("new/Division/", views.DivisionCreateView.as_view(), name="division_create"),
    path(
        "division/<str:pk>/update/",
        views.DivisionUpdateView.as_view(),
        name="division_update",
    ),
    path(
        "division/<str:pk>/delete/",
        views.DivisionDeleteView.as_view(),
        name="division_delete",
    ),
    path("transfer/<str:pk>/", views.StudentTransferUpdateView.as_view(), name="student_transfer_update")
]

students/models.py
from decimal import ROUND_HALF_UP, Decimal

from core.base import BaseModel
from core.choices import ACADEMIC_YEAR_CHOICES, BLOOD_CHOICES, GENDER_CHOICES
from django.db import models
from django.urls import reverse_lazy
from versatileimagefield.fields import PPOIField, VersatileImageField


class Standard(BaseModel):
    name = models.CharField(max_length=50, help_text="Enter the standard name (e.g., Grade 1, Class 10)")
    description = models.TextField(blank=True, help_text="Enter a description for the standard")

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return self.name

    @staticmethod
    def get_list_url():
        return reverse_lazy("students:standard_list")

    def get_absolute_url(self):
        return reverse_lazy("students:standard_detail", kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse_lazy("students:standard_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("students:standard_delete", kwargs={"pk": self.pk})


class Division(BaseModel):
    standard = models.ForeignKey(Standard, on_delete=models.PROTECT)
    name = models.CharField("Division", max_length=50, help_text="Enter the division name (e.g., A, B)")
    tutor = models.ForeignKey(
        "employees.Employee",
        on_delete=models.PROTECT,
        limit_choices_to={"user__usertype": "teacher"},
    )
    description = models.TextField(blank=True, help_text="Enter a description for the standard")

    class Meta:
        ordering = ("name",)
        unique_together = ("standard", "name")

    def __str__(self):
        return f"{self.standard} {self.name}"

    @staticmethod
    def get_list_url():
        return reverse_lazy("students:division_list")

    def get_absolute_url(self):
        return reverse_lazy("students:division_detail", kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse_lazy("students:division_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("students:division_delete", kwargs={"pk": self.pk})

    def student_count(self):
        return Student.objects.filter(division=self).count()


def get_next_admission_number():
    latest_admission_number = Student.objects.aggregate(models.Max("admission_number"))["admission_number__max"]
    if latest_admission_number is not None:
        next_admission_number = latest_admission_number + 1
    else:
        next_admission_number = 1
    return next_admission_number


class Student(BaseModel):
    user = models.OneToOneField(
        "accounts.User",
        on_delete=models.PROTECT,
        limit_choices_to={
            "is_active": True,
            "usertype": "student",
            "is_superuser": False,
        },
        related_name="student",
    )
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    admission_number = models.CharField(
        max_length=25,
        unique=True,
    )
    standard = models.ForeignKey("students.Standard", on_delete=models.PROTECT, null=True)
    division = models.ForeignKey(
        Division,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="students",
    )
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    blood_group = models.CharField(max_length=300, choices=BLOOD_CHOICES, blank=True, null=True)
    date_of_joining = models.DateField(null=True, blank=True)
    religion = models.CharField(max_length=128, null=True, blank=True)
    bus_no = models.PositiveIntegerField(null=True, blank=True)
    father_name = models.CharField(max_length=200, blank=True, null=True)
    mother_name = models.CharField(max_length=200, blank=True, null=True)
    primary_contact_number = models.CharField(max_length=15, blank=True, null=True)
    secondary_contact_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    photo = VersatileImageField(blank=True, null=True, upload_to="employees/photos/")
    ppoi = PPOIField("Image PPOI")

    class Meta:
        ordering = ("first_name",)

    def __str__(self):
        return f"{self.fullname} ({self.admission_number})"

    @staticmethod
    def get_list_url():
        return reverse_lazy("students:student_list")

    def get_absolute_url(self):
        return reverse_lazy("students:student_detail", kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse_lazy("students:student_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("students:student_delete", kwargs={"pk": self.pk})

    @property
    def fullname(self):
        return f"{self.first_name} {self.last_name}" if self.last_name else self.first_name
    
    def has_current_year_fee(self):
        from core.views import get_current_academic_year
        return self.academicyearstudentfee_set.filter(
            academic_year=get_current_academic_year(),   
            is_active=True
        ).exists()

    # @staticmethod
    # def next_admission_number():
    #     max_admission_no = Student.objects.aggregate(models.Max("admission_number"))
    #     max_admission_no_no = (
    #         max_admission_no["admission_number__max"]
    #         if max_admission_no["admission_number__max"] is not None
    #         else 0
    #     )
    #     return max_admission_no_no + 1


class AcademicYearStudentFee(BaseModel):
    academic_year = models.CharField(max_length=128, choices=ACADEMIC_YEAR_CHOICES)
    student = models.ForeignKey("students.Student", on_delete=models.CASCADE) 
    school_fee = models.DecimalField(max_digits=10, decimal_places=2)
    donation_fee = models.DecimalField("Admission Fee", max_digits=10, decimal_places=2)
    pta_fee = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    class Meta:
        unique_together = ("academic_year", "student", "is_active")
        ordering = ("academic_year",)

    def __str__(self):
        return f"{self.academic_year} {self.student}"

    @staticmethod
    def get_list_url():
        return reverse_lazy("students:academic_year_student_fee_list")

    def get_absolute_url(self):
        return reverse_lazy("students:academic_year_student_fee_detail", kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse_lazy("students:academic_year_student_fee_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("students:academic_year_student_fee_delete", kwargs={"pk": self.pk})

    def generate_fee_structure(self):
        # Assume course_duration_months is fixed to 8 for July to February
        course_duration_months = 8
        month_list = [
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
            "January",
            "February",
        ]
        fee_structure_list = []

        # Calculate monthly fee without rounding
        monthly_fee = Decimal((self.school_fee - self.donation_fee) / course_duration_months)

        # Calculate the rounded fee to the nearest multiple of 100
        rounded_fee = Decimal(round(monthly_fee, -2)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

        # Calculate the rounding difference for the last month (February)
        rounding_difference = rounded_fee * course_duration_months - (self.school_fee - self.donation_fee)
        for i, month in enumerate(month_list):
            fee = rounded_fee if i < course_duration_months - 1 else (rounded_fee - rounding_difference).quantize(Decimal("0.01"))
            fee_structure = {"month": month, "fee": fee}
            fee_structure_list.append(fee_structure)
        return fee_structure_list

    def total_fee(self):
        additional_fees_qs = self.student.student_additional_fees.filter(academic_year=self.academic_year, is_active=True)
        additional_fees = sum([item.amount for item in additional_fees_qs])
        return self.school_fee + additional_fees

    def total_receipt(self):
        receipt_qs = self.student.student_fee_statement.filter(academic_year=self.academic_year, is_active=True)
        total_receipt_amount = sum([item.amount for item in receipt_qs])
        return total_receipt_amount

    def pending_fee(self):
        return self.total_fee() - self.total_receipt()


class StudentFeeStatement(BaseModel):
    academic_year = models.CharField(max_length=128, choices=ACADEMIC_YEAR_CHOICES)
    student = models.ForeignKey(
        "students.Student",
        on_delete=models.PROTECT,
        related_name="student_fee_statement",
    )
    account = models.ForeignKey(
        "accounting.Account",
        related_name="studentfeestatement_account",
        on_delete=models.PROTECT,
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    voucher_number = models.PositiveBigIntegerField("Receipt Number", null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Student Fee Receipt"
        verbose_name_plural = "StudentFee Receipts"

    def __str__(self):
        return f"{self.student} Fee Receipt"

    def get_absolute_url(self):
        return reverse_lazy("students:studentfeestatement_detail", kwargs={"pk": self.pk})

    @staticmethod
    def get_list_url():
        return reverse_lazy("students:studentfeestatement_list")

    def get_update_url(self):
        return reverse_lazy("students:studentfeestatement_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("students:studentfeestatement_delete", kwargs={"pk": self.pk})

students/forms.py
from django import forms
from students.models import Student,AcademicYearStudentFee


class StudentTransferForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ("standard", "division")


class TransferFeeForm(forms.ModelForm):
    class Meta:
        model = AcademicYearStudentFee
        fields = ("school_fee", "donation_fee", "pta_fee")

templates/students/academicyearstudentfee_detail.html
{% extends 'app/base.html' %}
{% load render_table from django_tables2 %}
{% load static %}

{% block title %} {{ object }} Franchise Details {% endblock %}



{% block content %}
 <div class="content container-fluid print-content">
    
    <div class="page-header">
        <div class="row">
          <div class="col-sm-12">
            <div class="page-sub-header">
                <div class="page-rightheader ms-md-auto">
                    <div class="btn-list">
              
                      <a href="javascript:void(0);" onclick="window.print();" class="btn btn-sm btn-white" title="Print"> <i
                          class="feather feather-printer"></i> </a>
              
                      <a href="{{object.get_update_url}}" class="btn btn-sm btn-white" data-bs-placement="top"
                        data-bs-toggle="tooltip" title="Edit"> <i class="text-primary feather feather-edit-3"></i> </a>
              
                      <a href="{{object.get_delete_url}}" class="btn btn-sm btn-white" data-bs-placement="top"
                        data-bs-toggle="tooltip" title="Delete"> <i class="text-danger feather feather-trash-2"></i> </a>
              
                    </div>
                  </div>
            </div>
        </div>
          <div class="col-12">
            <div class="card bg-white">
                
                <div class="card-body">
                  
                    <ul class="nav nav-tabs nav-tabs-solid nav-justified">
                        <li class="nav-item"><a class="nav-link active" href="#overview"
                                data-bs-toggle="tab">OverView</a></li>
                        <li class="nav-item"><a class="nav-link" href="#fee-structure"
                                data-bs-toggle="tab">Fee Structure</a></li>
                        
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane show active" id="overview">
                          {% if object %}
                          <div class="card content_card">
                            <div class="card-header">
                              <div class="card-title d-flex align-items-center w-100">
                                <h5 class="mb-0">{{object}}</h5>
                              </div>
                            </div>
                            <div class="card-body p-0">
                              <div class="table-responsive">
                                <table class="table table-hover info_table mb-0" style="width:100%;">
                                  <tbody>
                                    {% for name, value in object.get_fields|slice:"5:" %}
                                    {% if value %}
                                    <tr>
                                      <td> {{name}} </td>
                                      <td> {{ value }} </td>
                                    </tr>
                                    {% endif %}
                                    {% endfor %}
                                  </tbody>
                                </table>
                              </div>
                              
                            </div>
                    
                          </div>
                          {% else %}
                          <div class="card content_card">
                            <div class="card-body">
                              <p class="text-center">There is nothing here</p>
                            </div>
                          </div>
                          {% endif %}
                        </div>
                        <div class="tab-pane" id="fee-structure">
                          <div class="table-responsive">
                           
                            <table class="table table-hover">
                              <thead>
                                <tr>
                                    <th>Month</th>
                                    <th>Fee</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for fee in object.generate_fee_structure %}
                                    <tr>
                                        <td>{{ fee.month }}</td>
                                        <td>₹ {{ fee.fee }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            </table>
                          </div>
                        
                          
                        </div>
                    </div>
                </div>
            </div>
        </div>
          
        </div>
    </div>
   
</div>

{% endblock %}

templates/students/student_form.html
{% extends 'app/base.html' %}
{% load i18n crispy_forms_tags %}
{% load static %}

{% block title %} New/Change {{title}} {% endblock %}


{% block content %}
<div class="content container-fluid">
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col-sm-12">
                <div class="page-sub-header">
                    <h3 class="page-title">New/Change {{title}}</h3>
                   
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
               
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <form class="{% if form_class %} {{ form_class }} {% else %}form-horizontal {% endif %}" method="post" autocomplete="off" enctype="multipart/form-data">
                                
                                {% csrf_token %}
                                {{form|crispy}}
                                {{fee_form|crispy}}
                                <div class="my-4 text-end">
                                    <div class="form-group mb-0">
                                      <button type="submit" class="btn btn-primary me-2">{% translate "Save" %}</button>
                                      <button type="button" onclick="history.back()" class="border btn btn-outline-grey">
                                        {% translate "Cancel" %}</button>
                                    </div>
                                  </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block javascript %}
<script>
$(document).ready(function () {
    $("#id_standard").change(function () {
        let standardId = $(this).val();

        $("#id_division").empty().append('<option value="">---------</option>');

        if (standardId) {
            $.ajax({
                url: "/students/get-divisions/",
                type: "GET",
                data: { standard_id: standardId },
                success: function (response) {

                    $.each(response, function (index, division) {
                        $("#id_division").append(
                            $("<option>", {
                                value: division.id,
                                text: division.name
                            })
                        );
                    });

                    $("#id_division").trigger('change.select2');
                },
                error: function () {
                    alert("Error fetching divisions.");
                }
            });
        }
    });
});
</script>
{% endblock %}

templates/students/studenttransfer_form.html
{% extends 'app/base.html' %}
{% load i18n crispy_forms_tags %}
{% load static %}

{% block title %} New/Change {{title}} {% endblock %}


{% block content %}
<div class="content container-fluid">
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col-sm-12">
                <div class="page-sub-header">
                    <h3 class="page-title">New/Change {{title}}</h3>
                   
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
               
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <form class="{% if form_class %} {{ form_class }} {% else %}form-horizontal {% endif %}" method="post" autocomplete="off" enctype="multipart/form-data">
                                
                                {% csrf_token %}
                                {{form|crispy}}
                                {{fee_form|crispy}}
                                <div class="my-4 text-end">
                                    <div class="form-group mb-0">
                                      <button type="submit" class="btn btn-primary me-2">{% translate "Save" %}</button>
                                      <button type="button" onclick="history.back()" class="border btn btn-outline-grey">
                                        {% translate "Cancel" %}</button>
                                    </div>
                                  </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script>
$(document).ready(function () {
    $("#id_standard").change(function () {
        let standardId = $(this).val();

        $("#id_division").empty().append('<option value="">---------</option>');

        if (standardId) {
            $.ajax({
                url: "/students/get-divisions/",
                type: "GET",
                data: { standard_id: standardId },
                success: function (response) {

                    $.each(response, function (index, division) {
                        $("#id_division").append(
                            $("<option>", {
                                value: division.id,
                                text: division.name
                            })
                        );
                    });

                    $("#id_division").trigger('change.select2');
                },
                error: function () {
                    alert("Error fetching divisions.");
                }
            });
        }
    });
});
</script>
{% endblock %}