abcschool/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("core.urls", namespace="core")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("employees/", include("employees.urls", namespace="employees")),
        path("students/", include("students.urls", namespace="students")),
        path("accounting/", include("accounting.urls", namespace="accounting")),
        path("reports/", include("reports.urls", namespace="reports")),
        path("fees/", include("fees.urls", namespace="fees")),
        path("exams/", include("exams.urls", namespace="exams")),
        path("tasks/", include("tasks.urls", namespace="tasks")),
        path("courses/", include("courses.urls", namespace="courses")),
        path("hrms/", include("hrms.urls", namespace="hrms")),
        path("accounts/", include("registration.backends.default.urls")),
        path("tinymce/", include("tinymce.urls")),
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "ABC School Administration"
admin.site.site_title = "ABC School Admin Portal"
admin.site.index_title = "Welcome to ABC School Admin Portal"

accounting/urls.py
from django.urls import path

from . import views

app_name = "accounting"

urlpatterns = [
    path("accounts/", views.AccountListView.as_view(), name="account_list"),
    path("account/<str:pk>/", views.AccountDetailView.as_view(), name="account_detail"),
    path("new/account/", views.AccountCreateView.as_view(), name="account_create"),
    path(
        "account/<str:pk>/update/",
        views.AccountUpdateView.as_view(),
        name="account_update",
    ),
    path(
        "account/<str:pk>/delete/",
        views.AccountDeleteView.as_view(),
        name="account_delete",
    ),
    path(
        "expense_accounts/",
        views.ExpenseAccountListView.as_view(),
        name="expense_account_list",
    ),
    path(
        "expense_account/<str:pk>/",
        views.ExpenseAccountDetailView.as_view(),
        name="expense_account_detail",
    ),
    path(
        "new/expense_account/",
        views.ExpenseAccountCreateView.as_view(),
        name="expense_account_create",
    ),
    path(
        "expense_account/<str:pk>/update/",
        views.ExpenseAccountUpdateView.as_view(),
        name="expense_account_update",
    ),
    path(
        "expense_account/<str:pk>/delete/",
        views.ExpenseAccountDeleteView.as_view(),
        name="expense_account_delete",
    ),
    path("expenses/", views.ExpenseListView.as_view(), name="expense_list"),
    path("expense/<str:pk>/", views.ExpenseDetailView.as_view(), name="expense_detail"),
    path("new/expense/", views.ExpenseCreateView.as_view(), name="expense_create"),
    path(
        "expense/<str:pk>/update/",
        views.ExpenseUpdateView.as_view(),
        name="expense_update",
    ),
    path(
        "expense/<str:pk>/delete/",
        views.ExpenseDeleteView.as_view(),
        name="expense_delete",
    ),
    path(
        "expense_payments/",
        views.ExpensePaymentListView.as_view(),
        name="expense_payment_list",
    ),
    path(
        "expense_payment/<str:pk>/",
        views.ExpensePaymentDetailView.as_view(),
        name="expense_payment_detail",
    ),
    path(
        "new/expense_payment/<str:pk>/",
        views.ExpensePaymentCreateView.as_view(),
        name="expense_payment_create",
    ),
    path(
        "expense_payment/<str:pk>/update/",
        views.ExpensePaymentUpdateView.as_view(),
        name="expense_payment_update",
    ),
    path(
        "expense_payment/<str:pk>/delete/",
        views.ExpensePaymentDeleteView.as_view(),
        name="expense_payment_delete",
    ),
    path(
        "income_accounts/",
        views.IncomeAccountListView.as_view(),
        name="income_account_list",
    ),
    path(
        "income_account/<str:pk>/",
        views.IncomeAccountDetailView.as_view(),
        name="income_account_detail",
    ),
    path(
        "new/income_account/",
        views.IncomeAccountCreateView.as_view(),
        name="income_account_create",
    ),
    path(
        "income_account/<str:pk>/update/",
        views.IncomeAccountUpdateView.as_view(),
        name="income_account_update",
    ),
    path(
        "income_account/<str:pk>/delete/",
        views.IncomeAccountDeleteView.as_view(),
        name="income_account_delete",
    ),
    path("incomes/", views.IncomeListView.as_view(), name="income_list"),
    path("income/<str:pk>/", views.IncomeDetailView.as_view(), name="income_detail"),
    path("new/income/", views.IncomeCreateView.as_view(), name="income_create"),
    path(
        "income/<str:pk>/update/",
        views.IncomeUpdateView.as_view(),
        name="income_update",
    ),
    path(
        "income/<str:pk>/delete/",
        views.IncomeDeleteView.as_view(),
        name="income_delete",
    ),
    path("contras/", views.ContraListView.as_view(), name="contra_list"),
    path("contra/<str:pk>/", views.ContraDetailView.as_view(), name="contra_detail"),
    path("new/contra/", views.ContraCreateView.as_view(), name="contra_create"),
    path(
        "contra/<str:pk>/update/",
        views.ContraUpdateView.as_view(),
        name="contra_update",
    ),
    path(
        "contra/<str:pk>/delete/",
        views.ContraDeleteView.as_view(),
        name="contra_delete",
    ),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("suggestions/", views.SuggestionListView.as_view(), name="suggestion_list"),
    path(
        "suggestion/<str:pk>/",
        views.SuggestionDetailView.as_view(),
        name="suggestion_detail",
    ),
    path(
        "new/suggestion/",
        views.SuggestionCreateView.as_view(),
        name="suggestion_create",
    ),
    path(
        "suggestion/<str:pk>/update/",
        views.SuggestionUpdateView.as_view(),
        name="suggestion_update",
    ),
    path(
        "suggestion/<str:pk>/delete/",
        views.SuggestionDeleteView.as_view(),
        name="suggestion_delete",
    ),
]

employees/urls.py
from django.urls import path

from . import views

app_name = "employees"

urlpatterns = [
    path("", views.EmployeeListView.as_view(), name="employee_list"),
    path("employee/<str:pk>/", views.EmployeeDetailView.as_view(), name="employee_detail"),
    path("new/employee/", views.EmployeeCreateView.as_view(), name="employee_create"),
    path(
        "new/employee/<str:pk>/",
        views.EmployeeCreateView.as_view(),
        name="employee_create",
    ),
    path(
        "employee/<str:pk>/update/",
        views.EmployeeUpdateView.as_view(),
        name="employee_update",
    ),
    path(
        "employee/<str:pk>/delete/",
        views.EmployeeDeleteView.as_view(),
        name="employee_delete",
    ),
    path("designations/", views.DesignationListView.as_view(), name="designation_list"),
    path(
        "designation/<str:pk>/",
        views.DesignationDetailView.as_view(),
        name="designation_detail",
    ),
    path(
        "new/designation/",
        views.DesignationCreateView.as_view(),
        name="designation_create",
    ),
    path(
        "designation/<str:pk>/update/",
        views.DesignationUpdateView.as_view(),
        name="designation_update",
    ),
    path(
        "designation/<str:pk>/delete/",
        views.DesignationDeleteView.as_view(),
        name="designation_delete",
    ),
    path("departments/", views.DepartmentListView.as_view(), name="department_list"),
    path(
        "department/<str:pk>/",
        views.DepartmentDetailView.as_view(),
        name="department_detail",
    ),
    path(
        "new/department/",
        views.DepartmentCreateView.as_view(),
        name="department_create",
    ),
    path(
        "department/<str:pk>/update/",
        views.DepartmentUpdateView.as_view(),
        name="department_update",
    ),
    path(
        "department/<str:pk>/delete/",
        views.DepartmentDeleteView.as_view(),
        name="department_delete",
    ),
    path(
        "employeepayrolls/",
        views.EmployeePayrollListView.as_view(),
        name="employeepayroll_list",
    ),
    path(
        "employeepayroll/<str:pk>/",
        views.EmployeePayrollDetailView.as_view(),
        name="employeepayroll_detail",
    ),
    path(
        "new/employeepayroll/",
        views.EmployeePayrollCreateView.as_view(),
        name="employeepayroll_create",
    ),
    path(
        "employeepayroll/<str:pk>/update/",
        views.EmployeePayrollUpdateView.as_view(),
        name="employeepayroll_update",
    ),
    path(
        "employeepayroll/<str:pk>/delete/",
        views.EmployeePayrollDeleteView.as_view(),
        name="employeepayroll_delete",
    ),
    path(
        "employeepayment/",
        views.EmployeePaymentListView.as_view(),
        name="employeepayment_list",
    ),
    path(
        "employeepayment/<str:pk>/",
        views.EmployeePaymentDetailView.as_view(),
        name="employeepayment_detail",
    ),
    path(
        "new/employeepayment/",
        views.EmployeePaymentCreateView.as_view(),
        name="employeepayment_create",
    ),
    path(
        "employeepayment/<str:pk>/update/",
        views.EmployeePaymentUpdateView.as_view(),
        name="employeepayment_update",
    ),
    path(
        "employeepayment/<str:pk>/delete/",
        views.EmployeePaymentDeleteView.as_view(),
        name="employeepayment_delete",
    ),
]

hrms/urls.py
from django.urls import path

from . import views

app_name = "hrms"

urlpatterns = [
    path(
        "leave_request/",
        views.LeaveRequestListView.as_view(),
        name="leave_request_list",
    ),
    path(
        "leave_request/<str:pk>/",
        views.LeaveRequestDetailView.as_view(),
        name="leave_request_detail",
    ),
    path(
        "new/leave_request/",
        views.LeaveRequestCreateView.as_view(),
        name="leave_request_create",
    ),
    path(
        "leave_request/<str:pk>/update/",
        views.LeaveRequestUpdateView.as_view(),
        name="leave_request_update",
    ),
    path(
        "leave_request/<str:pk>/delete/",
        views.LeaveRequestDeleteView.as_view(),
        name="leave_request_delete",
    ),
    path(
        "leave_request/<str:pk>/update_status/",
        views.leave_request_status_update,
        name="leave_request_status_update",
    ),
    path(
        "attendence/<str:pk>/update_status/",
        views.attendence_status_update,
        name="attendence_status_update",
    ),
    path("attendance/", views.AttendanceListView.as_view(), name="attendance_list"),
    path(
        "attendance/<str:pk>/",
        views.AttendanceDetailView.as_view(),
        name="attendance_detail",
    ),
    path(
        "new/attendance/",
        views.AttendanceCreateView.as_view(),
        name="attendance_create",
    ),
    path(
        "attendance/<str:pk>/delete/",
        views.AttendanceDeleteView.as_view(),
        name="attendance_delete",
    ),
]

students/urls.py
from django.urls import path

from . import views

app_name = "students"

urlpatterns = [
    #ajax 
    path("get-divisions/", views.get_divisions, name="get_divisions"),
    path("", views.StudentListView.as_view(), name="student_list"),
    path("student/<str:pk>/", views.StudentDetailView.as_view(), name="student_detail"),
    path("new/student/", views.StudentCreateView.as_view(), name="student_create"),
    path(
        "new/student/<str:pk>/",
        views.StudentCreateView.as_view(),
        name="student_create",
    ),
    path(
        "student/<str:pk>/update/",
        views.StudentUpdateView.as_view(),
        name="student_update",
    ),
    path(
        "student/<str:pk>/delete/",
        views.StudentDeleteView.as_view(),
        name="student_delete",
    ),
    path(
        "studentfeestatements/",
        views.StudentFeeStatementListView.as_view(),
        name="studentfeestatement_list",
    ),
    path(
        "studentfeestatement/<str:pk>/",
        views.StudentFeeStatementDetailView.as_view(),
        name="studentfeestatement_detail",
    ),
    path(
        "new/studentfeestatement/",
        views.StudentFeeStatementCreateView.as_view(),
        name="studentfeestatement_create",
    ),
    path(
        "studentfeestatement/<str:pk>/update/",
        views.StudentFeeStatementUpdateView.as_view(),
        name="studentfeestatement_update",
    ),
    path(
        "studentfeestatement/<str:pk>/delete/",
        views.StudentFeeStatementDeleteView.as_view(),
        name="studentfeestatement_delete",
    ),
    path(
        "academic_year_student_fees/",
        views.AcademicYearStudentFeeListView.as_view(),
        name="academic_year_student_fee_list",
    ),
    path(
        "academic_year_student_fee/<str:pk>/",
        views.AcademicYearStudentFeeDetailView.as_view(),
        name="academic_year_student_fee_detail",
    ),
    path(
        "new/academic_year_student_fee/",
        views.AcademicYearStudentFeeCreateView.as_view(),
        name="academic_year_student_fee_create",
    ),
    path(
        "academic_year_student_fee/<str:pk>/update/",
        views.AcademicYearStudentFeeUpdateView.as_view(),
        name="academic_year_student_fee_update",
    ),
    path(
        "academic_year_student_fee/<str:pk>/delete/",
        views.AcademicYearStudentFeeDeleteView.as_view(),
        name="academic_year_student_fee_delete",
    ),
    path("standards/", views.StandardListView.as_view(), name="standard_list"),
    path("standard/<str:pk>/", views.StandardDetailView.as_view(), name="standard_detail"),
    path("new/standard/", views.StandardCreateView.as_view(), name="standard_create"),
    path(
        "standard/<str:pk>/update/",
        views.StandardUpdateView.as_view(),
        name="standard_update",
    ),
    path(
        "standard/<str:pk>/delete/",
        views.StandardDeleteView.as_view(),
        name="standard_delete",
    ),
    path("divisions/", views.DivisionListView.as_view(), name="division_list"),
    path("division/<str:pk>/", views.DivisionDetailView.as_view(), name="division_detail"),
    path("new/Division/", views.DivisionCreateView.as_view(), name="division_create"),
    path(
        "division/<str:pk>/update/",
        views.DivisionUpdateView.as_view(),
        name="division_update",
    ),
    path(
        "division/<str:pk>/delete/",
        views.DivisionDeleteView.as_view(),
        name="division_delete",
    ),
    path("transfer/<str:pk>/", views.StudentTransferUpdateView.as_view(), name="student_transfer_update")
]

core/models.py
from django.db import models
from django.urls import reverse_lazy

from .base import BaseModel


class Suggestion(BaseModel):
    suggested_by = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    suggestion = models.TextField()

    def __str__(self):
        return f"{self.suggested_by} Suggestion"

    def get_absolute_url(self):
        return reverse_lazy("core:suggestion_detail", kwargs={"pk": self.pk})

    @staticmethod
    def get_list_url():
        return reverse_lazy("core:suggestion_list")

    def get_update_url(self):
        return reverse_lazy("core:suggestion_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("core:suggestion_delete", kwargs={"pk": self.pk})

templates/core/home.html
{% extends 'app/base.html' %}
{% load static %}
{% load render_table from django_tables2 %}

{% block title %} Home {% endblock %}

{% block content %}
<div class="content container-fluid">

    <div class="page-header">
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <div class="page-sub-header">
                    <h3 class="page-title">{{greeting}} {{ request.user }}!</h3>
                   
                </div>
            </div>
           
        </div>
    </div>

    {% if request.user.usertype != 'student' %}
    <div class="row ">
        <div class="col-12">
            <h5>Reports</h5>
        </div>
       
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <a href="{% url 'students:student_list' %}" class="stretched-link"></a>
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>Students Count</h6>
                            <h3>{{ students_count }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <a href="#" class="stretched-link"></a>
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>Divisions Count</h6>
                            <h3>{{ division_count }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if my_divisions %}
        {% for division in my_divisions %}

        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <a href="{% url 'core:home' %}?division__standard={{division.standard.pk}}&division__name__icontains={{division.name}}" class="stretched-link"></a>
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>{{ division }}</h6>
                            <h3> Students : {{ division.student_count }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
        {% if request.user.usertype == 'accountant' or request.user.usertype == 'management'%}
        
       
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <a href="{% url 'employees:employee_list' %}?user__usertype=teacher" class="stretched-link"></a>
                <div class="card-body">
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>Teachers</h6>
                            <h3>{{ teacher_count }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <a href="{% url 'employees:employee_list' %}?user__usertype=worker" class="stretched-link"></a>
                <div class="card-body">
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>Workers</h6>
                            <h3>{{ workers_count }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% for account in accounts %}
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <a href="{% url 'accounting:account_list' %}" class="stretched-link"></a>
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>{{account}} Balance</h6>
                            <h3>{{ account.balance }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
       {% endif %}

    </div>
    <div class="row">
        <div class="col-12">
            <h5>Today's Reports</h5>
        </div>
       
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <a href="{% url 'hrms:attendance_list' %}?date={{ now|date:'Y-m-d' }}&status=present" class="stretched-link"></a>
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>Today Present</h6>
                            <h3>{{ today_present }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <a href="{% url 'hrms:attendance_list' %}?date={{ now|date:'Y-m-d' }}&status=absent" class="stretched-link"></a>
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>Today Absent</h6>
                            <h3>{{ today_absent }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if request.user.usertype == 'management' or request.user.usertype == 'accountant' %}
        {% for account in accounts %}  
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>{{account}} Credit</h6>
                            <h3>{{ account.today_credit }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>{{account}} Debit</h6>
                            <h3>{{ account.today_expense }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-table comman-shadow">
                <div class="card-body">
                    
                    <div class="table-responsive">
                       
                        {% render_table table %}
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    {% else %}
    <div class="row ">
        
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>Total Fee</h6>
                            <h3>{{ current_school_fee|floatformat:2 }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <a href="{% url 'students:studentfeestatement_list' %}" class="stretched-link"></a>
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>Fee Paid</h6>
                            <h3>{{ total_paid|floatformat:2 }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <div class="card-body">
                    
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>Fee Pending</h6>
                            <h3>{{ fee_pending|floatformat:2 }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        {% comment %}
        <div class="col-xl-2 col-sm-6 col-12 d-flex">
            <div class="card bg-comman w-100">
                <div class="card-body">
                    <div class="db-widgets d-flex justify-content-between align-items-center">
                        <div class="db-info">
                            <h6>Out Standing</h6>
                            <h3>{{ student_out_standing }} </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endcomment %}


    </div>
    {% endif %}
    
</div>

{% endblock %}