abcschool/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("core.urls", namespace="core")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("employees/", include("employees.urls", namespace="employees")),
        path("students/", include("students.urls", namespace="students")),
        path("accounting/", include("accounting.urls", namespace="accounting")),
        path("reports/", include("reports.urls", namespace="reports")),
        path("fees/", include("fees.urls", namespace="fees")),
        path("exams/", include("exams.urls", namespace="exams")),
        path("tasks/", include("tasks.urls", namespace="tasks")),
        path("courses/", include("courses.urls", namespace="courses")),
        path("hrms/", include("hrms.urls", namespace="hrms")),
        path("accounts/", include("registration.backends.default.urls")),
        path("tinymce/", include("tinymce.urls")),
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "ABC School Administration"
admin.site.site_title = "ABC School Admin Portal"
admin.site.index_title = "Welcome to ABC School Admin Portal"

accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.UserListView.as_view(), name="user_list"),
    path("user/<str:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("new/user/", views.UserCreateView.as_view(), name="user_create"),
    path("user/<str:pk>/update/", views.UserUpdateView.as_view(), name="user_update"),
    path("user/<str:pk>/delete/", views.UserDeleteView.as_view(), name="user_delete"),
    path("profile/", views.UserProfile.as_view(), name="profile"),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("suggestions/", views.SuggestionListView.as_view(), name="suggestion_list"),
    path(
        "suggestion/<str:pk>/",
        views.SuggestionDetailView.as_view(),
        name="suggestion_detail",
    ),
    path(
        "new/suggestion/",
        views.SuggestionCreateView.as_view(),
        name="suggestion_create",
    ),
    path(
        "suggestion/<str:pk>/update/",
        views.SuggestionUpdateView.as_view(),
        name="suggestion_update",
    ),
    path(
        "suggestion/<str:pk>/delete/",
        views.SuggestionDeleteView.as_view(),
        name="suggestion_delete",
    ),
]

exams/urls.py
from django.urls import path

from . import views

app_name = "exams"

urlpatterns = [
    path("series/", views.SeriesListView.as_view(), name="series_list"),
    path("series/<str:pk>/", views.SeriesDetailView.as_view(), name="series_detail"),
    path("new/series/", views.SeriesCreateView.as_view(), name="series_create"),
    path(
        "series/<str:pk>/update/",
        views.SeriesUpdateView.as_view(),
        name="series_update",
    ),
    path(
        "series/<str:pk>/delete/",
        views.SeriesDeleteView.as_view(),
        name="series_delete",
    ),
    path("exams/", views.ExamListView.as_view(), name="exam_list"),
    path("exam/<str:pk>/", views.ExamDetailView.as_view(), name="exam_detail"),
    path("new/exam/", views.ExamCreateView.as_view(), name="exam_create"),
    path("exam/<str:pk>/update/", views.ExamUpdateView.as_view(), name="exam_update"),
    path("exam/<str:pk>/delete/", views.ExamDeleteView.as_view(), name="exam_delete"),
    path("student_exams/", views.StudentExamListView.as_view(), name="student_exam_list"),
    path(
        "student_exam/<str:pk>/",
        views.StudentExamDetailView.as_view(),
        name="student_exam_detail",
    ),
    path(
        "new/student_exam/",
        views.StudentExamCreateView.as_view(),
        name="student_exam_create",
    ),
    path(
        "student_exam/<str:pk>/update/",
        views.StudentExamUpdateView.as_view(),
        name="student_exam_update",
    ),
    path(
        "student_exam/<str:pk>/delete/",
        views.StudentExamDeleteView.as_view(),
        name="student_exam_delete",
    ),
    path(
        "student_mark/<str:pk>/update/",
        views.student_mark_update,
        name="student_mark_update",
    ),
]

hrms/urls.py
from django.urls import path

from . import views

app_name = "hrms"

urlpatterns = [
    path(
        "leave_request/",
        views.LeaveRequestListView.as_view(),
        name="leave_request_list",
    ),
    path(
        "leave_request/<str:pk>/",
        views.LeaveRequestDetailView.as_view(),
        name="leave_request_detail",
    ),
    path(
        "new/leave_request/",
        views.LeaveRequestCreateView.as_view(),
        name="leave_request_create",
    ),
    path(
        "leave_request/<str:pk>/update/",
        views.LeaveRequestUpdateView.as_view(),
        name="leave_request_update",
    ),
    path(
        "leave_request/<str:pk>/delete/",
        views.LeaveRequestDeleteView.as_view(),
        name="leave_request_delete",
    ),
    path(
        "leave_request/<str:pk>/update_status/",
        views.leave_request_status_update,
        name="leave_request_status_update",
    ),
    path(
        "attendence/<str:pk>/update_status/",
        views.attendence_status_update,
        name="attendence_status_update",
    ),
    path("attendance/", views.AttendanceListView.as_view(), name="attendance_list"),
    path(
        "attendance/<str:pk>/",
        views.AttendanceDetailView.as_view(),
        name="attendance_detail",
    ),
    path(
        "new/attendance/",
        views.AttendanceCreateView.as_view(),
        name="attendance_create",
    ),
    path(
        "attendance/<str:pk>/delete/",
        views.AttendanceDeleteView.as_view(),
        name="attendance_delete",
    ),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path("tasks/", views.TaskListView.as_view(), name="task_list"),
    path("task/<str:pk>/", views.TaskDetailView.as_view(), name="task_detail"),
    path("new/task/", views.TaskCreateView.as_view(), name="task_create"),
    path("task/<str:pk>/update/", views.TaskUpdateView.as_view(), name="task_update"),
    path("task/<str:pk>/delete/", views.TaskDeleteView.as_view(), name="task_delete"),
    path("student_tasks/", views.StudentTaskListView.as_view(), name="student_task_list"),
    path(
        "student_task/<str:pk>/",
        views.StudentTaskDetailView.as_view(),
        name="student_task_detail",
    ),
    path(
        "new/student_task/",
        views.StudentTaskCreateView.as_view(),
        name="student_task_create",
    ),
    path(
        "student_task/<str:pk>/update/",
        views.StudentTaskUpdateView.as_view(),
        name="student_task_update",
    ),
    path(
        "student_task/<str:pk>/delete/",
        views.StudentTaskDeleteView.as_view(),
        name="student_task_delete",
    ),
    path(
        "task/<str:pk>/update_status/",
        views.task_status_update,
        name="task_status_update",
    ),
]

templates/app/partials/attendence_status_form.html
{% if can_add %}
<form action="{% url 'hrms:attendence_status_update' record.pk %}" method="GET" class="attendence_update_form">
    <select name="status" id="status" class="form-control niceselect" style="width:auto">
        <option value="present" {% if record.status == 'present' %} selected {% endif %}>Present</option>
        <option value="absent" {% if record.status == 'absent' %} selected {% endif %}>Absent</option>
    </select>
</form>
<input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">

{% else %}

<span class="fw-bolder"> {{ record.get_status_display }} </span>

{% endif %}

templates/app/partials/filter.html
{% load i18n crispy_forms_tags %}

<div class="modal fade" id="filterModal" data-bs-backdrop="static"
data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Advanced Filter</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal"
                aria-label="Close"></button>
        </div>
            <form action="" method="get">
                <div class="modal-body">
                    <div class="row">
                        {% for field in filter.form %}
                        <div class="col-12">
                            <div class="form-group">
                                {{ field.errors }}
                                {{ field|as_crispy_field }}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="{{ request.url }}" class="btn btn-white me-auto border">{% translate "Reset" %}</a>
                    <a href="javascript:void(0);" class="btn btn-outline-white border" data-bs-dismiss="modal">
                        {% translate "Cancel" %}</a>
                    <button type="submit" class="btn btn-primary">{% translate "Apply" %}</button>
                </div>
            </form>
       
    </div>
</div>
</div>

templates/app/partials/header.html
{% load static %}

<div class="header">

    <div class="header-left">

        <a href="/" class="logo mx-auto">
            <img src="{% static 'web/img/logo.png' %}" alt="Logo">
        </a>
        <a href="{% url 'core:home' %}" class="logo logo-small">
            <img src="{% static 'web/img/logo-small.png' %}" alt="Logo" width="30" height="30">
        </a>
    </div>

    <div class="menu-toggle">
        <a href="javascript:void(0);" id="toggle_btn">
            <i class="fas fa-bars"></i>
        </a>
    </div>

    <div class="top-nav-search">
        {% comment %}
        <form action="{% url 'core:home' %}">
            <input type="text" class="form-control" name="q" value="{{query}}" placeholder="Search here">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
        </form>
        {% endcomment %}
    </div>


    <a class="mobile_btn" id="mobile_btn">
        <i class="fas fa-bars"></i>
    </a>


    <ul class="nav user-menu">

        <li class="nav-item zoom-screen me-2">
            <a href="#" class="nav-link header-nav-list win-maximize">
                <img src="{% static 'web/img/icons/header-icon-04.svg' %}" alt="">
            </a>
        </li>

        <li class="nav-item dropdown has-arrow new-user-menus">
            <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                <span class="user-img">
                    {% if current_user.photo %}
                    <img class="rounded-circle" src="{{ current_user.photo.url }}" width="40" height="40"
                        alt="{{ current_user.username }}">
                    {% else %}
                    <img class="rounded-circle" src="{{ default_user_avatar }}" width="40" height="40"
                        alt="{{ current_user.username }}">
                    {% endif %}
                    <div class="user-text">
                        <h6>{{ name }}</h6>
                        {% if current_user.user.employee %}
                        <p class="text-muted mb-0">{{ current_user.user.employee.designation }}</p>
                        {% else %}
                        <p class="text-muted mb-0">{{ current_user.user.get_usertype_display }}</p>
                        {% endif %}
                    </div>
                </span>
            </a>
            <div class="dropdown-menu">
                <div class="user-header">
                    <div class="avatar avatar-sm">
                        {% if current_user.photo %}
                        <img src="{{current_user.photo.url}}" alt="User Image" class="avatar-img rounded-circle">
                        {% else %}
                        <img src="{{default_user_avatar}}" alt="User Image" class="avatar-img rounded-circle">
                        {% endif %}
                    </div>
                    <div class="user-text">
                        <h6>{{ name }}</h6>
                        {% if current_user.user.employee %}
                        <p class="text-muted mb-0">{{ current_user.user.employee.designation }}</p>
                        {% else %}
                        <p class="text-muted mb-0">{{ current_user.user.get_usertype_display }}</p>
                        {% endif %}
                    </div>
                </div>


                <a class="dropdown-item" href="{% url 'accounts:profile' %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'auth_password_change' %}">Change Password</a>
                <a class="dropdown-item" href="{% url 'auth_logout' %}">Logout</a>
            </div>
        </li>

    </ul>

</div>

templates/app/partials/leave_request_status_form.html
{% if can_edit %}
<form action="{% url 'hrms:leave_request_status_update' record.pk %}" method="GET" class="leave_request_update_form">
    <select name="status" id="status" class="form-control niceselect" style="width:auto">
        <option value="pending" {% if record.status == 'pending' %} selected {% endif %}>Pending</option>
        <option value="approved" {% if record.status == 'approved' %} selected {% endif %}>Approved</option>
        <option value="rejected" {% if record.status == 'rejected' %} selected {% endif %}>Rejected</option>
    </select>
</form>
<input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">

{% else %}

<span class="fw-bolder"> {{ record.get_status_display }} </span>

{% endif %}

templates/app/partials/marks_obtained_form.html
{% if can_add %}
<form action="{% url 'exams:student_mark_update' record.pk %}" method="GET" class="exam_mark_update_form">
    <input type="number" value="{{record.marks_obtained}}" name="marks_obtained" min="0" class="numberinput form-control " id="id_marks_obtained" style="width: 100px;">
</form>
<input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">

{% else %}

<span class="fw-bolder"> {{ record.marks_obtained }} </span>

{% endif %}

templates/app/partials/quick_view.html
<button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#Task_{{record.pk}}">
    View
</button>

<div class="modal fade" id="Task_{{record.pk}}" data-bs-backdrop="static"
data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">{{ record.suggested_by }} Suggestion</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal"
                aria-label="Close"></button>
        </div>
        <div class="modal-body">
           {{ record.suggestion }}
        </div>
    </div>
</div>
</div>

templates/app/partials/report_filter.html
{% load i18n crispy_forms_tags %}

<div class="modal fade" id="filterModal" data-bs-backdrop="static"
data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Advanced Filter</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal"
                aria-label="Close"></button>
        </div>
            <form action="" method="get">
                <div class="modal-body">
                    <div class="row">
                        {% for field in form %}
                        <div class="col-12">
                            <div class="form-group">
                                {{ field.errors }}
                                {{ field|as_crispy_field }}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-white me-auto border">{% translate "Reset" %}</button>
                    <a href="javascript:void(0);" class="btn btn-outline-white border" data-bs-dismiss="modal">
                        {% translate "Cancel" %}</a>
                    <button type="submit" class="btn btn-primary">{% translate "Apply" %}</button>
                </div>
            </form>
       
    </div>
</div>
</div>

templates/app/partials/table_actions.html
<a href="{{ record.get_absolute_url }}" class="btn btn-sm btn-light btn-outline-info">OPEN</a>

templates/app/partials/task_status_form.html
<form action="{% url 'tasks:task_status_update' record.pk %}" method="GET" class="task_update_form">
    <select name="status" id="status" class="form-control niceselect" style="width:auto">
        {% if request.user.usertype == 'student' %}
            {% if record.status == 'assigned' %}
            <option value="assigned" {% if record.status == 'assigned' %} selected {% endif %}>Assigned</option>
            {% endif %}
            <option value="in_review" {% if record.status == 'in_review' %} selected {% endif %}>In Review</option>
            {% if record.status == 'rework' %}
            <option value="rework" {% if record.status == 'rework' %} selected {% endif %}>Rework</option>
            {% endif %}
        {% else %}
            <option value="assigned" {% if record.status == 'assigned' %} selected {% endif %}>Assigned</option>
            <option value="in_review" {% if record.status == 'in_review' %} selected {% endif %}>In Review</option>
            <option value="rework" {% if record.status == 'rework' %} selected {% endif %}>Rework</option>
            <option value="completed" {% if record.status == 'completed' %} selected {% endif %}>Completed</option>
        {% endif %}
    </select>
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
</form>